spring:
  application:
    name: eCommoerce
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test' #IN-Memory Mode
    #url: 'jdbc:h2:~/test'  #Embedded Mode
    username: sa
    password:

  h2:
    console: #H2 DB? ??? ??? ? ?? ??
      enabled: true     #H2 Console ?? ??
      path: /h2-console #H2 Console ????

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none #spring.jpa.ddl-auto 를 통해 설정 가능
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    root: DEBUG
#      springframework: DEBUG
server:
  port: 80

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method