version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_test
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  db:
    image: mysql:8.4.2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #root_password
      MYSQL_DATABASE: eCommerce # 기존 DB 이름 반영
      MYSQL_USER: user #user
      MYSQL_PASSWORD: password #user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data: