version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_test
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

  db:
    image: mysql:8.4.2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #root_password
      MYSQL_DATABASE: eCommerce # 기존 DB 이름 반영
      MYSQL_USER: user #user
      MYSQL_PASSWORD: password #user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: