CREATE TABLE IF NOT EXISTS "USERS" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    POINT INTEGER,
    CREATED_AT TIMESTAMP
);

-- Create PRODUCT table
CREATE TABLE IF NOT EXISTS "PRODUCT" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE INTEGER,
    QUANTITY INTEGER,
    CREATED_AT TIMESTAMP
);

-- Create PAYMENT table (assuming it's also a JPA entity)
CREATE TABLE IF NOT EXISTS "PAYMENT" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT,
    PRICE INTEGER,
    STATUS VARCHAR(255),
    CREATED_AT TIMESTAMP
);

-- Create ORDER_HISTORY table (assuming it's a record)
CREATE TABLE IF NOT EXISTS "ORDER_HISTORY" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT,
    PRODUCT_ID BIGINT,
    PRICE INTEGER,
    STATUS VARCHAR(255),
    YYYY_MM_DD VARCHAR(8),
    CREATED_AT TIMESTAMP
);

-- Create ORDER table (assuming it's a record)
CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    PRODUCT_ID BIGINT,
    QUANTITY INTEGER,
    PRICE INTEGER,
    STATUS VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- Create CART table
CREATE TABLE IF NOT EXISTS "CART" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT,
    PRODUCT_ID BIGINT,
    QUANTITY INTEGER,
    CREATED_AT TIMESTAMP
);
